# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(508, 348)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.ledButton = QtWidgets.QPushButton(self.centralwidget)
        self.ledButton.setObjectName("ledButton")
        self.verticalLayout_2.addWidget(self.ledButton)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.voltage = QtWidgets.QLabel(self.centralwidget)
        self.voltage.setText("")
        self.voltage.setObjectName("voltage")
        self.verticalLayout.addWidget(self.voltage)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.bottom = QtWidgets.QGroupBox(self.centralwidget)
        self.bottom.setStyleSheet("QWidget {\n"
"    background-color: #fff\n"
"}")
        self.bottom.setObjectName("bottom")
        self.gridLayout = QtWidgets.QGridLayout(self.bottom)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.bottomBack = QtWidgets.QFrame(self.bottom)
        self.bottomBack.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottomBack.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottomBack.setObjectName("bottomBack")
        self.horizontalLayout_2.addWidget(self.bottomBack)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.bottomLeft = QtWidgets.QFrame(self.bottom)
        self.bottomLeft.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottomLeft.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottomLeft.setObjectName("bottomLeft")
        self.horizontalLayout_3.addWidget(self.bottomLeft)
        self.bottomRight = QtWidgets.QFrame(self.bottom)
        self.bottomRight.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottomRight.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottomRight.setObjectName("bottomRight")
        self.horizontalLayout_3.addWidget(self.bottomRight)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.horizontalLayout_4.addWidget(self.bottom)
        self.horizontalLayout_4.setStretch(0, 10)
        self.horizontalLayout_4.setStretch(1, 30)
        self.horizontalLayout_4.setStretch(2, 50)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 508, 22))
        self.menubar.setObjectName("menubar")
        self.menuCrazyChair = QtWidgets.QMenu(self.menubar)
        self.menuCrazyChair.setObjectName("menuCrazyChair")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionRecord_Data = QtWidgets.QAction(MainWindow)
        self.actionRecord_Data.setObjectName("actionRecord_Data")
        self.menuCrazyChair.addAction(self.actionRecord_Data)
        self.menubar.addAction(self.menuCrazyChair.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "LED Switch"))
        self.ledButton.setText(_translate("MainWindow", "On"))
        self.label_2.setText(_translate("MainWindow", "Voltage"))
        self.menuCrazyChair.setTitle(_translate("MainWindow", "CrazyChair"))
        self.actionRecord_Data.setText(_translate("MainWindow", "Record Data"))

