# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(558, 460)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.back = QtWidgets.QGroupBox(self.centralwidget)
        self.back.setStyleSheet("QWidget {\n"
"    background-color: #fff\n"
"}")
        self.back.setObjectName("back")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.back)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.backLeft = QtWidgets.QFrame(self.back)
        self.backLeft.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.backLeft.setFrameShadow(QtWidgets.QFrame.Raised)
        self.backLeft.setObjectName("backLeft")
        self.horizontalLayout_5.addWidget(self.backLeft)
        self.backRight = QtWidgets.QFrame(self.back)
        self.backRight.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.backRight.setFrameShadow(QtWidgets.QFrame.Raised)
        self.backRight.setObjectName("backRight")
        self.horizontalLayout_5.addWidget(self.backRight)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.backDown = QtWidgets.QFrame(self.back)
        self.backDown.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.backDown.setFrameShadow(QtWidgets.QFrame.Raised)
        self.backDown.setObjectName("backDown")
        self.verticalLayout.addWidget(self.backDown)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.back)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.bottom = QtWidgets.QGroupBox(self.centralwidget)
        self.bottom.setStyleSheet("QWidget {\n"
"    background-color: #fff\n"
"}")
        self.bottom.setObjectName("bottom")
        self.gridLayout = QtWidgets.QGridLayout(self.bottom)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.bottomBack = QtWidgets.QFrame(self.bottom)
        self.bottomBack.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottomBack.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottomBack.setObjectName("bottomBack")
        self.horizontalLayout_2.addWidget(self.bottomBack)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.bottomLeft = QtWidgets.QFrame(self.bottom)
        self.bottomLeft.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottomLeft.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottomLeft.setObjectName("bottomLeft")
        self.horizontalLayout_3.addWidget(self.bottomLeft)
        self.bottomRight = QtWidgets.QFrame(self.bottom)
        self.bottomRight.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottomRight.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottomRight.setObjectName("bottomRight")
        self.horizontalLayout_3.addWidget(self.bottomRight)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.bottom)
        self.verticalLayout_4.setStretch(1, 100)
        self.verticalLayout_4.setStretch(3, 100)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setAlignment(QtCore.Qt.AlignCenter)
        self.label1.setObjectName("label1")
        self.verticalLayout_2.addWidget(self.label1)
        self.imageHolder = QtWidgets.QLabel(self.centralwidget)
        self.imageHolder.setText("")
        self.imageHolder.setObjectName("imageHolder")
        self.verticalLayout_2.addWidget(self.imageHolder)
        self.verticalLayout_2.setStretch(1, 100)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.gridLayout_3.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 558, 22))
        self.menubar.setObjectName("menubar")
        self.menuCrazyChair = QtWidgets.QMenu(self.menubar)
        self.menuCrazyChair.setObjectName("menuCrazyChair")
        MainWindow.setMenuBar(self.menubar)
        self.actionRecord_Data = QtWidgets.QAction(MainWindow)
        self.actionRecord_Data.setObjectName("actionRecord_Data")
        self.actionSetting = QtWidgets.QAction(MainWindow)
        self.actionSetting.setObjectName("actionSetting")
        self.menuCrazyChair.addAction(self.actionRecord_Data)
        self.menuCrazyChair.addAction(self.actionSetting)
        self.menubar.addAction(self.menuCrazyChair.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "Back"))
        self.label_3.setText(_translate("MainWindow", "Buttom"))
        self.label1.setText(_translate("MainWindow", "Posture"))
        self.menuCrazyChair.setTitle(_translate("MainWindow", "CrazyChair"))
        self.actionRecord_Data.setText(_translate("MainWindow", " Record Data"))
        self.actionSetting.setText(_translate("MainWindow", " Setting"))

