# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Setting.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Setting(object):
    def setupUi(self, Setting):
        Setting.setObjectName("Setting")
        Setting.setEnabled(True)
        Setting.resize(473, 211)
        self.gridLayout = QtWidgets.QGridLayout(Setting)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkVibrate = QtWidgets.QCheckBox(Setting)
        self.checkVibrate.setObjectName("checkVibrate")
        self.verticalLayout.addWidget(self.checkVibrate)
        self.checkPopUp = QtWidgets.QCheckBox(Setting)
        self.checkPopUp.setObjectName("checkPopUp")
        self.verticalLayout.addWidget(self.checkPopUp)
        self.checkPhone = QtWidgets.QCheckBox(Setting)
        self.checkPhone.setObjectName("checkPhone")
        self.verticalLayout.addWidget(self.checkPhone)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textVibrate = QtWidgets.QTextEdit(Setting)
        self.textVibrate.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textVibrate.sizePolicy().hasHeightForWidth())
        self.textVibrate.setSizePolicy(sizePolicy)
        self.textVibrate.setMaximumSize(QtCore.QSize(78, 30))
        self.textVibrate.setObjectName("textVibrate")
        self.horizontalLayout.addWidget(self.textVibrate)
        self.label = QtWidgets.QLabel(Setting)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.textPopUp = QtWidgets.QTextEdit(Setting)
        self.textPopUp.setMaximumSize(QtCore.QSize(78, 30))
        self.textPopUp.setObjectName("textPopUp")
        self.horizontalLayout_2.addWidget(self.textPopUp)
        self.label_3 = QtWidgets.QLabel(Setting)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.textPhone = QtWidgets.QTextEdit(Setting)
        self.textPhone.setMaximumSize(QtCore.QSize(78, 30))
        self.textPhone.setObjectName("textPhone")
        self.horizontalLayout_3.addWidget(self.textPhone)
        self.label_2 = QtWidgets.QLabel(Setting)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(108, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(Setting)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_4.addWidget(self.buttonBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 1)

        self.retranslateUi(Setting)
        self.buttonBox.accepted.connect(Setting.accept)
        self.buttonBox.rejected.connect(Setting.reject)
        QtCore.QMetaObject.connectSlotsByName(Setting)

    def retranslateUi(self, Setting):
        _translate = QtCore.QCoreApplication.translate
        Setting.setWindowTitle(_translate("Setting", "Setting"))
        self.checkVibrate.setText(_translate("Setting", "Vibration alarm every"))
        self.checkPopUp.setText(_translate("Setting", "Pop out window alarm every"))
        self.checkPhone.setText(_translate("Setting", "Phone notification alarm every"))
        self.label.setText(_translate("Setting", "bad posture detection"))
        self.label_3.setText(_translate("Setting", "bad posture detection"))
        self.label_2.setText(_translate("Setting", "bad posture detection"))

